kind: Pod 
apiVersion: v1 
metadata:
  name: nginx-pod-resources
spec: 
  containers:
  - name: nginx-container
    image: nginx:1.14
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "1"
        memory: "500Mi"

