kind: Pod 
apiVersion: v1 
metadata: 
  name: nginx-liveness-pod 
spec: 
  containers:
  - name: nginx-container 
    image: nginx:1.14 
    ports: 
    - containerPort: 80
    
    livenessProbe:
      httpGet:
        path: /
        port: 80
      
      periodSeconds: 10
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 1
