kind: Pod
apiVersion: v1
metadata:
  name: tensorflow-gpu
spec:
  containers:
  - name: tensorflow
    image: tensorflow/tensorflow:nightly-jupyter
    ports:
    - containerPort: 888
      protocol: TCP
  nodeSelector:
    gpu: "true"
    