kind: Deployment 
apiVersion: apps/v1 
metadata:
  name: dep-mainui
  annotations:
    kubernetes.io/change-cause: httpd:2.4
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      name: httpd-pod
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
      - name: httpd-container
        image: httpd:2.4
        ports:
        - containerPort: 80
        
