apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web 
      version: blue 
  template:
    metadata:
      labels:
        app: web 
        version: blue 
    spec:
      containers:
      - name: mainui
        image: whatwant/node-web:2.0
        ports:
        - containerPort: 8080

