apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web 
      version: green 
  template:
    metadata:
      labels:
        app: web 
        version: green 
    spec:
      containers:
      - name: mainui
        image: whatwant/node-web:3.0
        ports:
        - containerPort: 8080

