apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod
  name: testpod
  namespace: default
  resourceVersion: "429820"
  uid: 81b4d92e-15a1-48eb-99f3-2251dce3aa04
spec:
  containers:
  - image: nginx
    name: testpod
    ports:
    - containerPort: 80
      protocol: TCP
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jd4lt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: pod-viewer
  volumes:
  - name: kube-api-access-jd4lt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-05T08:11:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-05T08:11:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-05T08:11:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-05T08:11:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://546b7295fbd7c8cc5703a20027d94c1e0386396f1e21438b71eea0918318c7cf
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:6db391d1c0cfb30588ba0bf72ea999404f2764febf0f1f196acd5867ac7efa7e
    lastState: {}
    name: testpod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-05T08:11:29Z"
  hostIP: 192.168.10.30
  phase: Running
  podIP: 10.233.75.44
  podIPs:
  - ip: 10.233.75.44
  qosClass: BestEffort
  startTime: "2024-04-05T08:11:25Z"
